misc: allow custom -userdatapath (closes #10)
jammsen/docker-sons-of-the-forest-dedicated-server pull request #11
Opened 2023-07-05 21:45 UTC by justmiles

2023-07-10 06:06 UTC, jammsen requested changes

2023-07-10 14:36 UTC, justmiles commented on usr/bin/servermanager.sh
> +USERDATA_PATH="${USERDATA_PATH:-/sonsoftheforest/userdata}"
This is bash shorthand to set a default variable if unset. We could certainty move the default to the Dockerfile if that's preferred.

It's definitely valid, though. Here's a quick example using an online compiler: http://tpcg.io/_PE7JLT

2023-07-10 14:37 UTC, justmiles commented on usr/bin/servermanager.sh
> +    if [ ! -f $CONFIGFILE_PATH ]; then
Makes sense, I'll add the `ownerswhitelist.txt` from your second example

2023-07-11 18:58 UTC, jammsen commented on usr/bin/servermanager.sh
> +USERDATA_PATH="${USERDATA_PATH:-/sonsoftheforest/userdata}"
Ahhh now i understand that line, i did never hear of this before, thats a lot for teaching me that!

But to be honest, i would prefer it the clean way, set all defaults in the Dockerfile and then you can overwrite it anyway you like after this.

2023-07-11 19:04 UTC, jammsen commented on usr/bin/servermanager.sh
> +USERDATA_PATH="${USERDATA_PATH:-/sonsoftheforest/userdata}"
Do you want to do this or should i do this?

2023-07-13 13:54 UTC, justmiles commented on usr/bin/servermanager.sh
> +USERDATA_PATH="${USERDATA_PATH:-/sonsoftheforest/userdata}"
Happy to update it. I'll knock it out shortly.

2023-07-17 23:11 UTC, justmiles commented
@jammsen this is ready for review.

2023-07-18 18:29 UTC, jammsen commented
Thanks @justmiles i didnt have time until yet, im gonna check this out now.

2023-07-18 18:37 UTC, merged

2023-07-18 19:19 UTC, jammsen commented
Hey @justmiles 
So aside from a windows-vs-unix encoding problem which can easily be solved by "dos2unix servermanager.sh" and missing chmod +x permissions which might be down to my setup, everything else is working just fine.

Im done pushing the image right now to Docker-Hub - Feel free to test it and give me a feedback if what you want to do works 😃